In [32]:
import pandas as pd

In [33]:
url="https://land.naver.com/news/trendReport.naver?page=5"

data= pd.read_html(url)

In [34]:
df=data[0]
temp=df.copy()

In [35]:
df_temp=temp['제목'].str.replace('%',"")
df_temp

0     [12월2주 전국]전국-0.33, 서울-0.29, 수도권-0.35
1     [12월1주 전국]전국-0.33, 서울-0.23, 수도권-0.35
2     [11월4주 전국]전국-0.31, 서울-0.25, 수도권-0.35
3     [11월3주 전국]전국-0.26, 서울-0.36, 수도권-0.30
4     [11월2주 전국]전국-0.31, 서울-0.23, 수도권-0.34
5     [11월1주 전국]전국-0.33, 서울-0.33, 수도권-0.39
6     [10월4주 전국]전국-0.19, 서울-0.11, 수도권-0.20
7     [10월3주 전국]전국-0.30, 서울-0.27, 수도권-0.36
8     [10월2주 전국]전국-0.20, 서울-0.13, 수도권-0.25
9     [10월1주 전국]전국-0.25, 서울-0.28, 수도권-0.29
10    [9월5주 전국] 전국-0.11, 서울-0.12, 수도권-0.11
11    [9월4주 전국] 전국-0.11, 서울-0.24, 수도권-0.16
12    [9월3주 전국] 전국-0.02, 서울 0.04, 수도권 0.00
13    [9월2주 전국] 전국-0.12, 서울-0.13, 수도권-0.14
14    [9월1주 전국] 전국-0.12, 서울-0.12, 수도권-0.14
15    [8월4주 전국] 전국-0.01, 서울 0.06, 수도권 0.01
16    [8월3주 전국] 전국-0.08, 서울-0.01, 수도권-0.06
17    [8월2주 전국] 전국-0.10, 서울-0.10, 수도권-0.12
18    [8월1주 전국] 전국-0.05, 서울-0.02, 수도권-0.04
19    [7월5주 전국] 전국-0.03, 서울-0.01, 수도권-0.04
Name: 제목, dtype: object

In [36]:
regions=['전국','서울','수도권']
for region in regions:
    df_temp=df_temp.str.replace(region,"")

df_temp

0     [12월2주 ]-0.33, -0.29, -0.35
1     [12월1주 ]-0.33, -0.23, -0.35
2     [11월4주 ]-0.31, -0.25, -0.35
3     [11월3주 ]-0.26, -0.36, -0.30
4     [11월2주 ]-0.31, -0.23, -0.34
5     [11월1주 ]-0.33, -0.33, -0.39
6     [10월4주 ]-0.19, -0.11, -0.20
7     [10월3주 ]-0.30, -0.27, -0.36
8     [10월2주 ]-0.20, -0.13, -0.25
9     [10월1주 ]-0.25, -0.28, -0.29
10    [9월5주 ] -0.11, -0.12, -0.11
11    [9월4주 ] -0.11, -0.24, -0.16
12    [9월3주 ] -0.02,  0.04,  0.00
13    [9월2주 ] -0.12, -0.13, -0.14
14    [9월1주 ] -0.12, -0.12, -0.14
15    [8월4주 ] -0.01,  0.06,  0.01
16    [8월3주 ] -0.08, -0.01, -0.06
17    [8월2주 ] -0.10, -0.10, -0.12
18    [8월1주 ] -0.05, -0.02, -0.04
19    [7월5주 ] -0.03, -0.01, -0.04
Name: 제목, dtype: object

In [37]:
df_temp=df_temp.str.split(']',expand=True)#스플릿

In [38]:
df_temp=df_temp[1].str.split(',',expand=True)#스플릿관련배움

In [39]:
df_temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       20 non-null     object
 1   1       20 non-null     object
 2   2       20 non-null     object
dtypes: object(3)
memory usage: 612.0+ bytes

In [40]:
df_temp=df_temp.astype(float)

In [41]:
temp[regions]=df_temp
temp

,번호,제목,등록일,조회수,전국,서울,수도권
0,1726,"[12월2주 전국]전국-0.33%, 서울-0.29%, 수도권-0.35%",2022.12.13,1987,-0.33,-0.29,-0.35
1,1725,"[12월1주 전국]전국-0.33%, 서울-0.23%, 수도권-0.35%",2022.12.05,2168,-0.33,-0.23,-0.35
2,1724,"[11월4주 전국]전국-0.31%, 서울-0.25%, 수도권-0.35%",2022.11.30,1743,-0.31,-0.25,-0.35
3,1723,"[11월3주 전국]전국-0.26%, 서울-0.36%, 수도권-0.30%",2022.11.21,2305,-0.26,-0.36,-0.30
4,1722,"[11월2주 전국]전국-0.31%, 서울-0.23%, 수도권-0.34%",2022.11.15,1947,-0.31,-0.23,-0.34
5,1721,"[11월1주 전국]전국-0.33%, 서울-0.33%, 수도권-0.39%",2022.11.04,2628,-0.33,-0.33,-0.39
6,1720,"[10월4주 전국]전국-0.19%, 서울-0.11%, 수도권-0.20%",2022.11.03,1267,-0.19,-0.11,-0.20
7,1719,"[10월3주 전국]전국-0.30%, 서울-0.27%, 수도권-0.36%",2022.10.25,2258,-0.30,-0.27,-0.36
8,1718,"[10월2주 전국]전국-0.20%, 서울-0.13%, 수도권-0.25%",2022.10.17,2199,-0.20,-0.13,-0.25
9,1717,"[10월1주 전국]전국-0.25%, 서울-0.28%, 수도권-0.29%",2022.10.12,1797,-0.25,-0.28,-0.29
10,1716,"[9월5주 전국] 전국-0.11%, 서울-0.12%, 수도권-0.11%",2022.09.30,2494,-0.11,-0.12,-0.11
11,1715,"[9월4주 전국] 전국-0.11%, 서울-0.24%, 수도권-0.16%",2022.09.23,2061,-0.11,-0.24,-0.16
12,1714,"[9월3주 전국] 전국-0.02%, 서울 0.04%, 수도권 0.00%",2022.09.22,1334,-0.02,0.04,0.00
13,1713,"[9월2주 전국] 전국-0.12%, 서울-0.13%, 수도권-0.14%",2022.09.08,2889,-0.12,-0.13,-0.14
14,1712,"[9월1주 전국] 전국-0.12%, 서울-0.12%, 수도권-0.14%",2022.09.06,1672,-0.12,-0.12,-0.14
15,1711,"[8월4주 전국] 전국-0.01%, 서울 0.06%, 수도권 0.01%",2022.08.29,2310,-0.01,0.06,0.01
16,1710,"[8월3주 전국] 전국-0.08%, 서울-0.01%, 수도권-0.06%",2022.08.19,2657,-0.08,-0.01,-0.06
17,1709,"[8월2주 전국] 전국-0.10%, 서울-0.10%, 수도권-0.12%",2022.08.12,2327,-0.10,-0.10,-0.12
18,1708,"[8월1주 전국] 전국-0.05%, 서울-0.02%, 수도권-0.04%",2022.08.11,1259,-0.05,-0.02,-0.04
19,1707,"[7월5주 전국] 전국-0.03%, 서울-0.01%, 수도권-0.04%",2022.08.02,2375,-0.03,-0.01,-0.04

In [42]:
df_rate = temp[['등록일']+regions+['번호']]